Date: Sat, 11 Oct 2008 00:48:01 +0200 (CEST)
From: test@localhost
To: test@localhost
Message-ID: urn:uuid:219365EB848AD9CACB1223678880948
Subject: Test
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="----=_Part_0_6727097.1223678881682"

------=_Part_0_6727097.1223678881682
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit

First part
------=_Part_0_6727097.1223678881682
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit

Second part
------=_Part_0_6727097.1223678881682--
